import "./ResultCard.css";
import jsPDF from "jspdf";

function ResultCard({ result }) {
  const score = result.score;
  const role = result.role;
  const skillsFound = result.skillsFound;
  const missingSkills = result.missingSkills;
  const suggestions = result.suggestions;
  const resumeTips = result.resumeTips;
  const statistics = result.statistics;
  const insights = result.insights;

  let feedback = "";
  let scoreColor = "";

  if (score >= 90) {
    feedback =
      "Excellent match for the selected role. Your resume demonstrates strong alignment with the required skills.";
    scoreColor = "#16a34a";
  } else if (score >= 70) {
    feedback =
      "Good match for the selected role. A few improvements can further strengthen your profile.";
    scoreColor = "#2563eb";
  } else if (score >= 50) {
    feedback =
      "Moderate match. Consider adding more relevant skills and projects.";
    scoreColor = "#eab308";
  } else {
    feedback =
      "Low match. Your resume lacks several key skills required for this role.";
    scoreColor = "#dc2626";
  }

  const downloadReport = () => {

    const doc = new jsPDF();

    let y = 20;

    doc.setFontSize(20);
    doc.text("AI Resume Analyzer", 20, y);

    y += 15;

    doc.setFontSize(12);

    doc.text(`Target Role: ${role}`, 20, y);

    y += 10;

    doc.text(`ATS Score: ${score}%`, 20, y);

    y += 15;

    doc.setFontSize(15);

    doc.text("Skills Found", 20, y);

    y += 10;

    skillsFound.forEach(skill => {
      doc.text("• " + skill, 25, y);
      y += 8;
    });

    y += 5;

    doc.text("Missing Skills", 20, y);

    y += 10;

    missingSkills.forEach(skill => {
      doc.text("• " + skill, 25, y);
      y += 8;
    });

    y += 5;

    doc.text("Suggestions", 20, y);

    y += 10;

    suggestions.forEach(item => {
      doc.text("• " + item, 25, y);
      y += 8;
    });

    y += 5;

    doc.text("Resume Tips", 20, y);

    y += 10;

    resumeTips.forEach(item => {
      doc.text("• " + item, 25, y);
      y += 8;
    });

    y += 5;

    doc.text("Generated by AI Resume Analyzer", 20, y);

    doc.save("ATS_Report.pdf");

  };

  return (
    <div className="result-card">
      <div className="score-section">
        <h2>ATS Score</h2>

        <p className="role-badge">Analyzed For: {role}</p>

        <h3 className="match-badge">
          {score >= 90
            ? "Excellent Match"
            : score >= 70
              ? "Good Match"
              : score >= 50
                ? "Moderate Match"
                : "Low Match"}
        </h3>

        <div
          className="score-circle"
          style={{
            background: scoreColor,
          }}
        >
          {score}%
        </div>

        <p className="score-label">ATS Compatibility Score</p>

        <p className="feedback-text">{feedback}</p>
      </div>

      <div className="result-grid">
        <div className="result-box">
          <h3>Skills Found</h3>

          <ul>
            {skillsFound.length === 0 ? (
              <p>No matching skills found for this role.</p>
            ) : (
              skillsFound.map((skill) => (
                <li key={skill} className="success-item">
                  ✓ {skill}
                </li>
              ))
            )}
          </ul>
        </div>

        <div className="result-box">
          <h3>Missing Skills</h3>

          <ul>
            {missingSkills.length === 0 ? (
              <p>Excellent! No missing skills detected for this role.</p>
            ) : (
              missingSkills.map((skill) => (
                <li key={skill} className="missing-item">
                  ✕ {skill}
                </li>
              ))
            )}
          </ul>
        </div>

        <div className="result-box full-width">
          <h3>Suggestions</h3>

          <ul>
            {suggestions.length === 0 ? (
              <p>Your resume aligns well with the selected role.</p>
            ) : (
              suggestions.map((suggestion) => (
                <li key={suggestion}>• {suggestion}</li>
              ))
            )}
          </ul>
        </div>

        <div className="result-box full-width">
          <h3>Resume Improvement Tips</h3>

          <ul>
            {resumeTips.length === 0 ? (
              <p>No additional resume improvement tips available.</p>
            ) : (
              resumeTips.map((tip) => <li key={tip}>• {tip}</li>)
            )}
          </ul>
        </div>

        <div className="result-box full-width">
          <h3>Resume Statistics</h3>

          <ul>
            <li>📄 Total Words: {statistics.wordCount}</li>
            <li>💻 Skills Matched: {statistics.matchedSkills}</li>
            <li>❌ Missing Skills: {statistics.missingSkills}</li>
            <li>🎯 Required Skills: {statistics.totalRequiredSkills}</li>
            <li>📊 Skill Coverage: {statistics.skillCoverage}%</li>
            <li>📜 Certifications Mentioned: {statistics.certificationCount}</li>
            <li>🎓 Education Mentions: {statistics.educationCount}</li>
          </ul>
        </div>

        <div className="result-box full-width">
          <h3>Resume Completeness</h3>

          <ul>
            <li>{statistics.completeness.email ? "✅" : "❌"} Email Address</li>
            <li>{statistics.completeness.phone ? "✅" : "❌"} Phone Number</li>
            <li>{statistics.completeness.github ? "✅" : "❌"} GitHub Profile</li>
            <li>{statistics.completeness.linkedin ? "✅" : "❌"} LinkedIn Profile</li>
            <li>{statistics.completeness.education ? "✅" : "❌"} Education Section</li>
            <li>{statistics.completeness.skills ? "✅" : "❌"} Skills Section</li>
          </ul>

          <p className="completeness-score">
            Overall Resume Completeness: {statistics.completenessPercentage}%
          </p>
        </div>

        <div className="result-box full-width">
          <h3>💡 AI Resume Insights</h3>

          {insights.map((item, index) => (
            <div key={index} className="insight-card">
              <h4>{item.question}</h4>
              <p>{item.answer}</p>
            </div>
          ))}
        </div>
        <div
          className="download-section"
        >

          <button
            className="download-btn"
            onClick={downloadReport}
          >

            ⬇ Download ATS Report

          </button>

        </div>
      </div>
    </div>
  );
}

export default ResultCard;